sudo: required

services:
  - docker


script:
    # Build image
    - docker-compose up -d

    # List running containers
    - docker ps -a

    # Wait to databases start
    - sleep 5

    # Chech the initial state
    - docker exec -it mysql.init mysql -u liquiuser -pliquipw liquidb -e "show tables;"
    - docker exec -it mysql.all mysql -u liquiuser -pliquipw liquidb -e "show tables;"

    # Run Version 1 - on Database Init (related to contexts)
    - docker exec -it myliqui.global bash -c 'cd $BUILDENV; exec "/app/run_init_1.sh"'

    # Check the modifications
    - docker exec -it mysql.init mysql -u liquiuser -pliquipw liquidb -e "desc person;"
    - docker exec -it mysql.init mysql -u liquiuser -pliquipw liquidb -e "show tables;"
    - docker exec -it mysql.init mysql -u liquiuser -pliquipw liquidb -e "show tables;" | grep -q person

    # Run Version 2 - on Database Init (related to contexts)
    - docker exec -it myliqui.global bash -c 'cd $BUILDENV; exec "/app/run_init_2.sh"'

    # Check the modifications
    - docker exec -it mysql.init mysql -u liquiuser -pliquipw liquidb -e "desc person;"
    - docker exec -it mysql.init mysql -u liquiuser -pliquipw liquidb -e "desc person;" | grep -q username

    # Run Version 1 - on Database All (related to contexts)
    - docker exec -it myliqui.global bash -c 'cd $BUILDENV; exec "/app/run_all_1.sh"'

    # Check the modifications
    - docker exec -it mysql.all mysql -u liquiuser -pliquipw liquidb -e "show tables;"
    - docker exec -it mysql.all mysql -u liquiuser -pliquipw liquidb -e "show tables;" | grep -q DATABASECHANGELOG
    - docker exec -it mysql.all mysql -u liquiuser -pliquipw liquidb -e "show tables;" | grep -q DATABASECHANGELOGLOCK

    # Run Version 2 - on Database All (related to contexts)
    - docker exec -it myliqui.global bash -c 'cd $BUILDENV; exec "/app/run_all_2.sh"'

    # Check the modifications
    - docker exec -it mysql.all mysql -u liquiuser -pliquipw liquidb -e "show tables;"
    - docker exec -it mysql.all mysql -u liquiuser -pliquipw liquidb -e "show tables;" | grep -q state

    # Test PhpMyAdmin on Database Init
    - curl http://127.0.0.1:8081/ | grep -q liquidb

    # Test PhpMyAdmin on Database All
    - curl http://127.0.0.1:8082/ | grep -q liquidb
